a=input('Digite algo:')
t=type(a)
print('O tipo primitivo desse valor é',t)
print('Só tem espaços?',a.isspace())
print('É alfabético?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Está em maiúsculas?',a.isupper())
print('Está em minúsculas?',a.islower())
print('Está capitalizado?',a.istitle())